/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaopeng_jnidome_JNIUtils */

#ifndef _Included_com_xiaopeng_jnidome_JNIUtils
#define _Included_com_xiaopeng_jnidome_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaopeng_jnidome_JNIUtils
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaopeng_jnidome_JNIUtils_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
